#!/bin/bash
set _JAVA_AWT_WM_NONREPARENTING=1
if command -v compton > /dev/null 2>&1; then
  # yay, compton
  compton -f &
elif command -v xcompmgr > /dev/null 2>&1; then
  # xcompmgr will do
  xcompmgr -f &
fi
